### ISSUE TITLE
Specific user id always returning 500 on helix/entitlements/drops

### ISSUE THREAD

**Issue by FIXMESTEVE** [twitchdev/issues#1017]
**Brief description**

For some reason, a specific customer is unable to redeem their items. If I try to get their list of entitlements through helix/entitlements/drops endpoint on postman, I always receive 500 internal server error. Any other `user_id` will work fine, but with that specific customer's `user_id` it's always 500.

For context the game is Rivals of Aether II (`game_id` 330654616) and we have drops campaigns that work pretty well so far, most customers are able to get their drops items ingame just fine.

**How to reproduce**

GET helix/entitlements/drops?user_id=39933194&game_id=330654616&fulfillment_status=CLAIMED

**Expected behavior**

Should return a list of entitlements

**Screenshots**

![image](https://github.com/user-attachments/assets/962d7034-93d6-4956-b6c3-b266fc60b83b)

**Additional context or questions**

**Comment by Hyrius** [comment]
I am the specific user affected, and some games still can't retrieve my entitlements. 
Most games work fine, but some don't. 
I've noticed that most mainstream titles function properly, but many smaller ones fail to access my entitlements.

If needed, I can provide a list of recent campaigns in which I didn't receive in-game rewards, most likely due to failed entitlement API requests.

**Comment by MaxHayman** [comment]
```

Unhandled exception. TwitchLib.Api.Core.Exceptions.InternalServerErrorException: The API answered with a 500 Internal Server Error. Please retry your request
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequestAsync(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at TwitchLib.Api.Core.ApiBase.TwitchGetGenericAsync[T](String resource, ApiVersion api, List`1 getParams, String accessToken, String clientId, String customBase)
   at Program.<Main>$(String[] args) in C:\Users\MaxHayman\RiderProjects\CloudCodeTwitchPoc\FakeGame\Program.cs:line 100
   at Program.<Main>(String[] args)
````

We are getting this issue too with this same user.

**Comment by Hyrius** [comment]
I searched the issue and I'm the user in pretty much all developer reports. 

https://discuss.dev.twitch.com/t/unable-to-get-entitlements-for-specific-user-500-status/59840
https://discuss.dev.twitch.com/t/internal-server-error-on-drops-entitlement-api-for-specific-user/63761

It's always me (the affected user). :( 
Let me know if I can help somehow. 
Please don't reset my inventory, I'm very fond of it! :P

**Comment by Hyrius** [comment]
@BarryCarlyon 
Since you were involved in both discussions, I'm pinging you here. 
Sorry to bother!

**Comment by BlueCakeWithCows** [comment]
We believe the issue has since been mitigated. Is this problem still affecting you?

**Comment by Hyrius** [comment]
<img width="562" height="587" alt="Image" src="https://github.com/user-attachments/assets/9eb447c4-7bd1-46ec-af3e-5d095578e959" /> 

I just tested it on @FIXMESTEVE's page and got the same result. 
Any chance you can verify it, Tom?

**Comment by thedist** [comment]
> We believe the issue has since been mitigated. Is this problem still affecting you?

It does not appear to be resolved. I've checked several users I know to be problematic (some with 100% failure rate, others with partial failures when calling the entitlements API), and they still have issues.

**Comment by BlueCakeWithCows** [comment]
Ack. Investigating.

**Comment by Hyrius** [comment]
Even on https://www.twitch.tv/drops/inventory, it almost never loads at first. 
I have to refresh the page a few times for it to load properly. 



<img width="1363" height="675" alt="Image" src="https://github.com/user-attachments/assets/c6c0bc8d-3267-4eee-916c-907e92d76e72" /> 
After three or four refreshes, it loads!
<img width="1333" height="782" alt="Image" src="https://github.com/user-attachments/assets/34251e7e-8f6c-468b-afa3-b429905957ac" /> 



It happens no matter the browser, network, or device.
Even on the Android and iOS apps.


@BlueCakeWithCows 
This is the error when it doesn't load.
<img width="547" height="48" alt="Image" src="https://github.com/user-attachments/assets/6d69018e-fb04-4465-ac33-1c7ed4aa555f" />

**Comment by BlueCakeWithCows** [comment]
Thank you for the error log. We've applied a partial fix for the Helix API while we continue to root cause.

**Comment by FIXMESTEVE** [comment]
> I just tested it on [@FIXMESTEVE](https://github.com/FIXMESTEVE)'s page and got the same result. Any chance you can verify it, Tom?

I ran the request in postman again today, sometimes it returns error 500 and sometimes it returns data correctly, so there's some improvement.

**Comment by Hyrius** [comment]
@BlueCakeWithCows 

Might just be a coincidence, but I've noticed that games which linked using https://www.twitch.tv/activate still experience this error pretty much 100% of the time.

For example, **33 Immortals** and **No Rest For The Wicked** simply can't check my entitlements.  
Most (if not all) other games seem to be working very consistently, though.

> 2026-01-24T14:48:11.939|E|37400||TwitchAPIManager - <GetDropsEntitlements>b__0 : HTTP/1.1 500 Internal Server Error  
2026-01-24T14:48:11.939|E|37400||HTTP/1.1 500 Internal Server Error 

(Source: No Rest For The Wicked Player.log)

**Comment by thedist** [comment]
I don't think this is something that's related to which OAuth flow is used, because as an example I just did a quick test with an App token and requests with @Hyrius's `user_id` param results in a 500 every single time, similarly I have several other users which consistently have 100% failure rate, and also some users who have errors but at least have some occasional success's so can be handled with sufficient retrying.

**Comment by Hyrius** [comment]
I agree it is very probably unrelated, but it's so weird that some games always had 100% success rate and now most of them do. 
I just noticed that the ones who have 100% failure rate are almost guaranteed to use this OAuth flow for some reason.

**Comment by MaxHayman** [comment]
@Hyrius is it working with Phasmophiobia now?

**Comment by Hyrius** [comment]
@MaxHayman I don't think so... To be honest I don't know how to check. 

![Image](https://github.com/user-attachments/assets/ea8ef859-1324-40f1-a98b-ee09a6e83d0f)
Connection seems to be good, but...

<img width="362" height="419" alt="Image" src="https://github.com/user-attachments/assets/d02e80ab-2ad9-4705-8447-cf1540beebe7" />

It doesn't matter where I click, nothing changes... 
Which is weird, I'm sure I had at least one drop before.

**Comment by Hyrius** [comment]
@MaxHayman Just claimed the new drop and yeah, it doesn't work. 
I also tried reconnecting the Twitch account, and it says it worked and is properly linked, but no luck.

<img width="360" height="412" alt="Image" src="https://github.com/user-attachments/assets/bcabf415-c18b-472a-ab6b-a7da9cc93eff" />

Well, at least the prestige badge is back to showing up in the list.

**Comment by Hyrius** [comment]
@MaxHayman 

<img width="198" height="356" alt="Image" src="https://github.com/user-attachments/assets/c2a052af-fab2-4af4-9c7e-7a1b6f01e252" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/fc93c71e-a685-4029-8de9-9a778c9a5fdf" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0558df05-f5c0-4158-8561-aec6197abeb8" />

**Comment by Xemdo** [comment]
The original problem should be solved, but if it does happen to persist please ensure you are utilizing both the **user_id** and **game_id** query parameters. This is a known issue that is planned to be fixed in the future.

If you are utilizing both query parameters and still see HTTP 500 errors, let us know and we'll investigate those issues separately.

_Internal context: DEVREL-281_

**Comment by Hyrius** [comment]
Sorry to revive this issue, but my inventory hasn't been loading for over two days now.

The console reports a timeout fairly quickly. I'm not sure if it's related to this issue, but I've checked with several other people and it seems to be affecting only me.

Just like in the original report, I'm currently the only affected user I know of.

<img width="804" height="176" alt="Image" src="https://github.com/user-attachments/assets/a1499d11-a90c-4172-8214-035afd92f183" /> 

@Xemdo Any idea what might be causing this? 
I can still progress and claim drops, but the inventory itself isn't loading.

**Comment by Hyrius** [comment]
I'm still getting drops. Even though I can't see my inventory anymore, I can still earn and receive them in (most) games.
I just claimed one of the Marvel Rivals drops, and when I clicked the Claim button, my inventory suddenly loaded up!
Then I claimed another one (I had multiple drops to claim on the same page), and everything disappeared again...
Oh well, I just thought I'd mention it.

**Comment by Xemdo** [comment]
@Hyrius For individual user issues unrelated to the API calls, please open a support ticket:
https://help.twitch.tv/s/contactsupport

**Comment by Hyrius** [comment]
> [@Hyrius](https://github.com/Hyrius) For individual user issues unrelated to the API calls, please open a support ticket: https://help.twitch.tv/s/contactsupport

This is absolutely not an individual issue unrelated to the API calls. It's exactly what's described in this issue.

It hasn't been fixed yet, but yeah, I just wanted to let you know. At this point, it's been going on for so many years that I don't really know what to expect anymore.

Sorry.

(I've also opened multiple support tickets for this very issue in the past. I've just opened another one, as you suggested.)

**Comment by thedist** [comment]
> This is absolutely not an individual issue unrelated to the API calls. It's exactly what's described in this issue.

API calls on the Twitch site itself, are beyond the scope of this repo as this is specifically for 3rd party services such as those listed here [https://dev.twitch.tv/docs](https://dev.twitch.tv/docs) which is what game developers would be using to fulfil Drops redemptions. Where as the Twitch site itself, and any other 1st party services, are handled through Twitch Support which is why although it's all Drops related, it's separate from the Helix endpoint mentioned in this thread.
