### ISSUE TITLE
Embedded stream script failed to read the `localStorage` property from `Window`

### ISSUE THREAD

**Issue by twinpixxx** [twitchdev/issues#532]
**Brief description**
Embedded stream script trying to get access to the `localStorage` in Chrome Incognito Mode.
**How to reproduce**
Add embed player using iframe, ex: 
```
<iframe src="https://player.twitch.tv/?channel=dota2ruhub&parent=www.example.com" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>
```
Open page in incognito mode.
Get error for each embedded iframe in console:
```
Failed to get log level override from local storage.
 {err: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new e (https://static.twitchcdn.net/assets/player-main-4a55ef8996d54802ca61.js:1:857231)
    at Le (https://static.twitchcdn.net/assets/player-main-4a55ef8996d54802ca61.js:1:855766)
    at Object.443800 (https://static.twitchcdn.net/assets/player-main-4a55ef8996d54802ca61.js:1:550425)
    at i (https://player.twitch.tv/?video=1212796244&parent=site.stage.projectx-vg.com&mute=true&autoplay=false:1:10365)
    at t (https://static.twitchcdn.net/assets/player-main-4a55ef8996d54802ca61.js:1:2087864)
    at https://static.twitchcdn.net/assets/player-main-4a55ef8996d54802ca61.js:1:2087927
    at Function.i.O (https://player.twitch.tv/?video=1212796244&parent=site.stage.projectx-vg.com&mute=true&autoplay=false:1:10767)
    at https://static.twitchcdn.net/assets/player-main-4a55ef8996d54802ca61.js:1:2087962
    at a (https://player.twitch.tv/?video=1212796244&parent=site.stage.projectx-vg.com&mute=true&autoplay=false:1:103856)
    at https://static.twitchcdn.net/assets/player-main-4a55ef8996d54802ca61.js:1:73,
 key: 'twilight.minConsoleLogLevel'}
```
**Expected behavior**
There are no errors.

**Comment by Xemdo** [comment]
Unable to reproduce this. Accessing localStorage seems to have no issues from the iframe currently.
![image](https://github.com/twitchdev/issues/assets/11840265/b2ac3b96-0b76-44c5-8045-be2124679d52)
