### ISSUE TITLE
Cannot register application

### ISSUE THREAD

**Issue by ETisREAL** [twitchdev/issues#853]
When I try to create an application and set a callback url, I get an error: 
```
[GraphQL] One or more GraphQL errors were detected on request 01HDJWC3W7X00GCSBNEHBCA9VK. CreateOauthApp: service error [{…}]
(anonymous) @ dev-main-94b6a613e8ece18e0431.js:1
setTimeout (async)
(anonymous) @ dev-main-94b6a613e8ece18e0431.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
a @ vendor-e6c5101f9add5677f32f.js:1
Promise.then (async)
c @ vendor-e6c5101f9add5677f32f.js:1
a @ vendor-e6c5101f9add5677f32f.js:1
Promise.then (async)
c @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
h @ vendor-e6c5101f9add5677f32f.js:1
e.collectQueryStats @ dev-main-94b6a613e8ece18e0431.js:1
(anonymous) @ dev-main-94b6a613e8ece18e0431.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
h @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ dev-main-94b6a613e8ece18e0431.js:1
Promise.then (async)
(anonymous) @ dev-main-94b6a613e8ece18e0431.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
h @ vendor-e6c5101f9add5677f32f.js:1
apolloLinkFetch @ dev-main-94b6a613e8ece18e0431.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
e @ vendor-e6c5101f9add5677f32f.js:1
t.subscribe @ vendor-e6c5101f9add5677f32f.js:1
e.consumeQueue @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
setTimeout (async)
e.scheduleQueueConsumption @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
e @ vendor-e6c5101f9add5677f32f.js:1
t.subscribe @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
e @ vendor-e6c5101f9add5677f32f.js:1
t.subscribe @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ dev-main-94b6a613e8ece18e0431.js:1
e @ vendor-e6c5101f9add5677f32f.js:1
t.subscribe @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
Promise.then (async)
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
e @ vendor-e6c5101f9add5677f32f.js:1
t.subscribe @ vendor-e6c5101f9add5677f32f.js:1
complete @ vendor-e6c5101f9add5677f32f.js:1
t.start @ vendor-e6c5101f9add5677f32f.js:1
t @ vendor-e6c5101f9add5677f32f.js:1
e.getObservableFromLink @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
h @ vendor-e6c5101f9add5677f32f.js:1
e.mutate @ vendor-e6c5101f9add5677f32f.js:1
e.mutate @ vendor-e6c5101f9add5677f32f.js:1
t.mutate @ vendor-e6c5101f9add5677f32f.js:1
s.runMutation @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ sites.dev.pages.app-create-page-f2dd163a9e8ac83e862e.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
h @ vendor-e6c5101f9add5677f32f.js:1
t.onSave @ sites.dev.pages.app-create-page-f2dd163a9e8ac83e862e.js:1
d.onSave @ sites.dev.pages.app-create-page-f2dd163a9e8ac83e862e.js:1
s @ vendor-e6c5101f9add5677f32f.js:1
p @ vendor-e6c5101f9add5677f32f.js:1
(anonymous) @ vendor-e6c5101f9add5677f32f.js:1
m @ vendor-e6c5101f9add5677f32f.js:1
at @ vendor-e6c5101f9add5677f32f.js:1
ot @ vendor-e6c5101f9add5677f32f.js:1
st @ vendor-e6c5101f9add5677f32f.js:1
pt @ vendor-e6c5101f9add5677f32f.js:1
L @ vendor-e6c5101f9add5677f32f.js:1
U @ vendor-e6c5101f9add5677f32f.js:1
Jt @ vendor-e6c5101f9add5677f32f.js:1
Yt @ vendor-e6c5101f9add5677f32f.js:1
t.unstable_runWithPriority @ vendor-e6c5101f9add5677f32f.js:1
Wo @ vendor-e6c5101f9add5677f32f.js:1
N @ vendor-e6c5101f9add5677f32f.js:1
Gt @ vendor-e6c5101f9add5677f32f.js:1
vendor-e6c5101f9add5677f32f.js:1 Uncaught (in promise) Error: service error
    at new t (vendor-e6c5101f9add5677f32f.js:1:424291)
    at vendor-e6c5101f9add5677f32f.js:1:404496
    at n (vendor-e6c5101f9add5677f32f.js:1:381494)
    at vendor-e6c5101f9add5677f32f.js:1:381419
    at new Promise (<anonymous>)
    at Object.then (vendor-e6c5101f9add5677f32f.js:1:381385)
    at Object.next (vendor-e6c5101f9add5677f32f.js:1:381504)
    at x (vendor-e6c5101f9add5677f32f.js:1:444681)
    at _ (vendor-e6c5101f9add5677f32f.js:1:445187)
    at t.next (vendor-e6c5101f9add5677f32f.js:1:445720)
```

**How to reproduce**
Try to create an application and set a callback url

**Expected behavior**
It should create the application with its relatives URLs

**Screenshots**
![Screenshot from 2023-10-25 09-41-27](https://github.com/twitchdev/issues/assets/113307574/5aac3126-df7d-48fa-9c48-233906cd388f)

**Comment by Wissididom** [comment]
Most likely duplicate of #831

**Comment by ETisREAL** [comment]
It was a naming issue... TY @Wissididom
